<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Marketplace.Catalog.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Services\Catalog\Marketplace.Catalog.Infrastructure\Marketplace.Catalog.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Marketplace.Application" />
    <Using Include="Marketplace.Application.Abstractions" />
    <Using Include="Marketplace.Persistence" />
  </ItemGroup>

</Project>
