<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Marketplace.Catalog.Application.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Services\Catalog\Marketplace.Catalog.Application\Marketplace.Catalog.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Marketplace.Application" />
    <Using Include="Marketplace.Application.Abstractions" />
  </ItemGroup>

</Project>
